### ISSUE TITLE
Error when running. Traceback issue with Heroku URL? 

### ISSUE THREAD

**Issue by RosaEidola** [MageNume/bustabit-bot#1]
2020-07-17T17:04:49.193586+00:00 heroku[web.1]: Starting process with command `/bin/sh -c python3\ bot.py`
2020-07-17T17:04:52.090247+00:00 app[web.1]: Traceback (most recent call last):
2020-07-17T17:04:52.090265+00:00 app[web.1]:   File "bot.py", line 13, in <module>
2020-07-17T17:04:52.090266+00:00 app[web.1]:     URL = os.environ['**MY HEROKU URL IS HERE**']
2020-07-17T17:04:52.090266+00:00 app[web.1]:   File "/usr/lib/python3.8/os.py", line 675, in __getitem__
2020-07-17T17:04:52.090267+00:00 app[web.1]:     raise KeyError(key) from None
2020-07-17T17:04:52.090267+00:00 app[web.1]: KeyError: '**MY HEROKU URL IS HERE**/'
2020-07-17T17:04:52.152541+00:00 heroku[web.1]: Process exited with status 1
2020-07-17T17:04:52.203157+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by KylianCadet** [comment]
Replace `URL = os.environ['MY HEROKU URL IS HERE']` to `URL = 'MY HEROKU URL IS HERE'` in bot.py

**Comment by RosaEidola** [comment]
perfect, works fine now. I am now getting the below issue:

2020-07-17T17:34:27.806675+00:00 heroku[web.1]: Starting process with command `/bin/sh -c python3\ bot.py`
2020-07-17T17:34:29.733807+00:00 heroku[web.1]: Process exited with status 1
2020-07-17T17:34:29.769928+00:00 heroku[web.1]: State changed from starting to crashed
2020-07-17T17:34:29.690482+00:00 app[web.1]: firefox_profile must be a directory


The firefox profile is the same saved folder for the profile as per the instructions.

**Comment by RosaEidola** [comment]
(https://gyazo.com/7abe169ff3609d657cf7c6d9a5346732)

**Comment by KylianCadet** [comment]
I think you didn't commit it.
I've added `firefox_profile` to the .gitignore. I'm gonna remove it. Thanks !
You should remove `firefox_profile` from .gitignore and try to commit the folder.

**Comment by RosaEidola** [comment]
Ok that works perfectly! Thanks a lot for the help!
