### ISSUE TITLE
web driver issue

### ISSUE THREAD

**Issue by slayb3ar** [MageNume/bustabit-bot#8]
still looking into myself,  but I'm hitting a selenium issue and docker won't even start. (Seems to be new issue -had it working back in march). Just tried with a fresh clone and same problem.
```
butsabit_1  | Traceback (most recent call last):
butsabit_1  |   File "bot.py", line 185, in <module>
butsabit_1  |     bot = Bustabit(FIREFOX_DIR, SCRIPT_NAME)
butsabit_1  |   File "bot.py", line 104, in __init__
butsabit_1  |     self._webdriver = webdriver.Firefox(firefox_profile=profile_folder, options=opt)
butsabit_1  |   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
butsabit_1  |     RemoteWebDriver.__init__(
butsabit_1  |   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
butsabit_1  |     self.start_session(capabilities, browser_profile)
butsabit_1  |   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
butsabit_1  |     response = self.execute(Command.NEW_SESSION, parameters)
butsabit_1  |   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
butsabit_1  |     self.error_handler.check_response(response)
butsabit_1  |   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
butsabit_1  |     raise exception_class(message, screen, stacktrace)
butsabit_1  | selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0
butsabit_1  | 
bustabit-bot_butsabit_1 exited with code 1
```

**Comment by slayb3ar** [comment]
noticing code hasn’t changed lol, has to be new version of something (assuming firefox )

trying to hunt down old containers to find last working version @KylianCadet

**Comment by KylianCadet** [comment]
I've done a fresh installation, and it seems to work (localhost:8000 was running and showing me some logs).
From your docker logs i can only assume that the firefox profile you have provided is somehow bad. Maybe it is missing or it is too huge.

**Comment by slayb3ar** [comment]
@KylianCadet closing this as  issue has resolved itself. Still never found the root cause, but I suspect you were right about the Firefox profile (pretty much the only variable lol)

Anyway, thanks again. Great repo 👍
